---

name: " default"

on:
  push:
    branches:
    - '**'

jobs:
  # ensure all the basic pre-commit checks pass
  check:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: pre-commit
      uses: pre-commit/action@v2.0.3

  tag:
    needs: [check]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: release
      id: bump_semver
      uses: superblocksteam/github-tag-action@1.39.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true